# Generated by Django 2.0.6 on 2018-08-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180712_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='preview',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
